#!/usr/bin/env python3
"""Baseline measurement: run the CURRENT detect_scenes() on every fixture.

Writes .agents/research/baseline-detection.md documenting current behavior
(before the v2.1 rewrite) for before/after comparison.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SAMPLES = HERE.parent / "samples"
REPORT = HERE.parent.parent / ".agents" / "research" / "baseline-detection.md"

sys.path.insert(0, str(HERE.parent))

from scenecut.detect import detect_scenes  # noqa: E402


def main() -> None:
    gt = json.loads((SAMPLES / "ground_truth.json").read_text())
    rows = []
    for fx in gt["fixtures"]:
        name = fx["fixture"]
        path = SAMPLES / name
        if not path.exists():
            rows.append((name, fx["expected_cuts"], None, "MISSING FILE"))
            continue
        try:
            result = detect_scenes(str(path))
        except Exception as e:  # noqa: BLE001
            rows.append((name, fx["expected_cuts"], None, f"ERROR: {e}"))
            continue
        cuts = [
            {
                "frame": c["frame_num"],
                "type": c["type"],
                "conf": c.get("confidence"),
                "source": c.get("source"),
            }
            for c in result["cuts"]
            if c["frame_num"] > 0
        ]
        expected = fx["expected_cuts"]
        exp_frames = {c["frame"] for c in expected}
        got_frames = {c["frame"] for c in cuts}
        if not expected and cuts:
            verdict = f"FALSE POSITIVES ({len(cuts)} cuts on a no-cut fixture)"
        elif expected and not cuts:
            verdict = f"MISSES ALL ({len(expected)} expected)"
        elif exp_frames == got_frames:
            verdict = "EXACT MATCH"
        else:
            matched = exp_frames & got_frames
            extra = got_frames - exp_frames
            missing = exp_frames - got_frames
            verdict = (
                f"PARTIAL: {len(matched)}/{len(expected)} matched"
                + (f", +{len(extra)} extra" if extra else "")
                + (f", -{len(missing)} missing" if missing else "")
            )
        rows.append((name, expected, cuts, verdict))

    lines = [
        "# Baseline Detection Report (pre-rewrite)",
        "",
        "Current detector (PySceneDetect 0.7.1 4-pass heuristic + HSV dissolve sweep,",
        "default parameters) measured on the fault-injection fixture corpus.",
        "Generated by `scenecut_py/scripts/baseline_report.py`.",
        "",
        "| Fixture | Expected | Current cuts (frame/type/conf/source) | Verdict |",
        "|---|---|---|---|",
    ]
    for name, expected, cuts, verdict in rows:
        exp_str = ", ".join(f"{c['frame']}:{c['type_hint']}" for c in expected) or "none"
        if cuts is None:
            cuts_str = f"_{verdict}_"
            verdict = "ERROR"
        else:
            cuts_str = (
                ", ".join(
                    f"{c['frame']}/{c['type']}/{c['conf']}/{c['source']}" for c in cuts
                )
                or "none"
            )
        lines.append(f"| {name} | {exp_str} | {cuts_str} | {verdict} |")

    lines += [
        "",
        "## Interpretation notes",
        "",
        "- This is the BEFORE picture. The v2.1 rewrite (DECISIONS.md D3-D7) targets:",
        "  zero FPs on pan/sunset/static, correct typing on dissolve/match-dissolve/",
        "  fade-white, and preserved recall on hard cuts / reverse dialog.",
        "- Fixture intents + measured characteristics: see samples/ground_truth.json.",
        "",
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines))
    print(f"Wrote {REPORT}")
    for name, _e, _c, verdict in rows:
        print(f"  {name:32s} {verdict}")


if __name__ == "__main__":
    main()
